### ISSUE TITLE
Conflict with ClothConfig's save method

### ISSUE THREAD

**Issue by Madis0** [kyrptonaught/CMDKeybinds#2]
https://github.com/shedaniel/RoughlyEnoughItems/issues/181

May also break other mods' config, haven't had a chance to test yet.

Edit: clicking on this mod's config makes it crash. The creator of REI said "cmd keybinds [is] mixin into [the] cloth config save method".

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3.11.19 16:52
Description: mouseClicked event handler

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at me.shedaniel.clothconfig2.api.ConfigBuilder.create(ConfigBuilder.java:14)
	at net.kyrptonaught.cmdkeybind.config.ModMenuIntegration.buildScreen(ModMenuIntegration.java:34)
	at net.kyrptonaught.cmdkeybind.config.ModMenuIntegration.lambda$getConfigScreen$0(ModMenuIntegration.java:29)
	at java.util.Optional.map(Optional.java:215)
	at io.github.prospector.modmenu.api.ModMenuApi.lambda$getConfigScreenFactory$0(ModMenuApi.java:50)
	at io.github.prospector.modmenu.ModMenu.getConfigScreen(ModMenu.java:38)
	at io.github.prospector.modmenu.gui.ModListScreen.lambda$init$1(ModListScreen.java:94)
	at net.minecraft.class_4185.onPress(class_4185.java:18)
	at net.minecraft.class_4264.onClick(class_4264.java:15)
	at net.minecraft.class_339.mouseClicked(class_339.java:154)
	at net.minecraft.class_4069.mouseClicked(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:86)
	at net.minecraft.class_437.wrapScreenError(class_437.java:441)
	at net.minecraft.class_312.method_1601(class_312.java:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at net.minecraft.class_1041.method_16001(class_1041.java:503)
	at net.minecraft.class_1041.method_15998(class_1041.java:342)
	at net.minecraft.class_310.method_15994(class_310.java:1023)
	at net.minecraft.class_310.method_1523(class_310.java:976)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [net.kyrptonaught.cmdkeybind.json:MixinClothConfigScreen] from phase [DEFAULT] in config [net.kyrptonaught.cmdkeybind.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 33 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method onSave in net.kyrptonaught.cmdkeybind.json:MixinClothConfigScreen was not located in the target class me.shedaniel.clothconfig2.gui.ClothConfigScreen. Using refmap cmdkeybinds-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:387)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:296)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:264)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:244)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1145)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 33 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at me.shedaniel.clothconfig2.api.ConfigBuilder.create(ConfigBuilder.java:14)
	at net.kyrptonaught.cmdkeybind.config.ModMenuIntegration.buildScreen(ModMenuIntegration.java:34)
	at net.kyrptonaught.cmdkeybind.config.ModMenuIntegration.lambda$getConfigScreen$0(ModMenuIntegration.java:29)
	at java.util.Optional.map(Optional.java:215)
	at io.github.prospector.modmenu.api.ModMenuApi.lambda$getConfigScreenFactory$0(ModMenuApi.java:50)
	at io.github.prospector.modmenu.ModMenu.getConfigScreen(ModMenu.java:38)
	at io.github.prospector.modmenu.gui.ModListScreen.lambda$init$1(ModListScreen.java:94)
	at net.minecraft.class_4185.onPress(class_4185.java:18)
	at net.minecraft.class_4264.onClick(class_4264.java:15)
	at net.minecraft.class_339.mouseClicked(class_339.java:154)
	at net.minecraft.class_4069.mouseClicked(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:86)

-- Affected screen --
Details:
	Screen name: io.github.prospector.modmenu.gui.ModListScreen
Stacktrace:
	at net.minecraft.class_437.wrapScreenError(class_437.java:441)
	at net.minecraft.class_312.method_1601(class_312.java:86)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at net.minecraft.class_1041.method_16001(class_1041.java:503)
	at net.minecraft.class_1041.method_15998(class_1041.java:342)

-- Affected level --
Details:
	All players: 1 total; [class_746['robotkoer'/198, l='MpServer', x=674.92, y=55.00, z=165.88]]
	Chunk stats: Client Chunk Cache: 729, 441
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,66,240), Chunk: (at 0,4,0 in 0,15; contains blocks 0,0,240 to 15,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 180401 game time, 33355 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:574)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_310.method_1514(class_310.java:425)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:188)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Linux (amd64) version 4.19.80-1-MANJARO
	Java Version: 1.8.0_232, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2957591488 bytes (2820 MB) / 4496293888 bytes (4288 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecs: Amecs 1.2.5+1.14.4
		appleskin: AppleSkin 1.0.7
		autoconfig1: Auto Config v1 1.2.0+mc1.14.4
		autofish: Autofish 0.8.4
		blue_endless_jankson: jankson +
		blur: Blur 1.0.5
		cloth: Cloth Events 0.6.0
		cloth-config: Cloth Config 0.2.5
		cloth-config2: Cloth Config v2 1.7.3
		cmdkeybind: Command Macros 1.2.1
		consolehud: ConsoleHUD 1.0.3+build.6
		fabric: Fabric API 0.4.1+build.245-1.14
		fabric-api-base: Fabric API Base 0.1.1+2ac73e7242
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.0+591e97ae42
		fabric-commands-v0: Fabric Commands (v0) 0.1.1+591e97ae42
		fabric-containers-v0: Fabric Containers (v0) 0.1.2+591e97ae42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.1+591e97ae42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.1+591e97ae42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.0+369ab22e42
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.2+27da48aa46
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+591e97ae42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.0+591e97ae42
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+591e97ae42
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.0+591e97ae42
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463
		fabric-models-v0: Fabric Models (v0) 0.1.0+591e97ae42
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.0+c877038942
		fabric-networking-v0: Fabric Networking (v0) 0.1.3+591e97ae42
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.1+591e97ae42
		fabric-particles-v1: fabric-particles-v1 0.1.1+c877038942
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.2+591e97ae42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+591e97ae42
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.13+591e97ae42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.1+c877038942
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.2+36f27aa342
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.1+591e97ae42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.3+591e97ae42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.1+591e97ae42
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+591e97ae42
		fabricloader: Fabric Loader 0.6.3+build.168
		fiber2cloth: Fiber To Cloth 1.2.1
		lightoverlay: Light Overlay 3.5
		me_zeroeightsix_fiber: fiber 0.6.0-7
		minecraft: Minecraft 1.14.4
		mm: Manningham Mills 1.6
		modmenu: Mod Menu 1.7.14.1.14.4+build.126
		mousewheelie: Mouse Wheelie 1.3.4+1.14.4
		net_fabricmc_stitch: stitch 0.2.1.61
		optifabric: Optifabric 0.5.2
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		overheadhp: Over Head HP 0.1.2
		roughlyenoughitems: Roughly Enough Items 3.2.2+build.45
		shulkerboxtooltip: Shulker Box Tootip 1.3.1+1.14.4
		tweed: Tweed API 2.2.7
		voxelmap: VoxelMap 1.9.13
	Launched Version: fabric-loader-0.6.3+build.168-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: Mesa DRI Intel(R) Ivybridge Mobile  GL version 3.0 Mesa 19.2.2, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Stevens Traditional 64x64 [1.14.4] (Patch 1).zip, file/ST Customized Pack.zip, file/[1.11.2]+R3D+CRAFT+128x+(v0.3.1), file/Material+2.13.4.zip, file/Material HUD 2.2.1.zip, file/roboto-bold.zip, file/Anti-obtrusive, file/Disable menu music.zip, file/LowerShields.zip (incompatible), file/VanillaTweaks_r187101.zip
	Current Language: Eesti keel (Eesti)
	CPU: 4x Intel(R) Core(TM) i5-3360M CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0 Mesa 19.2.2
	OpenGlRenderer: Mesa DRI Intel(R) Ivybridge Mobile 
	OpenGlVendor: Intel Open Source Technology Center
	CpuCount: 4
```

**Comment by kyrptonaught** [comment]
Thank you for making me aware of this, fixed in 1.3.2
https://www.curseforge.com/minecraft/mc-mods/command-macros/files/2821459
