### ISSUE TITLE
I put the mod into my fabric launcher, bound a button and pushed it. Game crashed repeatedly.

### ISSUE THREAD

**Issue by Haui1112** [kyrptonaught/CMDKeybinds#45]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 08.04.23, 21:18
Description: Unexpected error

java.lang.NoSuchFieldError: field_40754
	at net.kyrptonaught.kyrptconfig.config.screen.NotSuckyButton.<init>(NotSuckyButton.java:12)
	at net.kyrptonaught.kyrptconfig.config.screen.ConfigSection.<init>(ConfigSection.java:23)
	at net.kyrptonaught.cmdkeybind.config.MacroScreenFactory.buildScreen(MacroScreenFactory.java:22)
	at net.kyrptonaught.cmdkeybind.CmdKeybindMod.lambda$onInitializeClient$0(CmdKeybindMod.java:34)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$4(ClientTickEvents.java:87)
	at net.minecraft.class_638.handler$zna000$fabric-lifecycle-events-v1$startWorldTick(class_638.java:2134)
	at net.minecraft.class_638.method_18116(class_638.java)
	at net.minecraft.class_310.method_1574(class_310.java:1813)
	at net.minecraft.class_310.method_1523(class_310.java:1101)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.kyrptonaught.kyrptconfig.config.screen.NotSuckyButton.<init>(NotSuckyButton.java:12)
	at net.kyrptonaught.kyrptconfig.config.screen.ConfigSection.<init>(ConfigSection.java:23)
	at net.kyrptonaught.cmdkeybind.config.MacroScreenFactory.buildScreen(MacroScreenFactory.java:22)
	at net.kyrptonaught.cmdkeybind.CmdKeybindMod.lambda$onInitializeClient$0(CmdKeybindMod.java:34)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$4(ClientTickEvents.java:87)
	at net.minecraft.class_638.handler$zna000$fabric-lifecycle-events-v1$startWorldTick(class_638.java:2134)
	at net.minecraft.class_638.method_18116(class_638.java)

-- Affected level --
Details:
	All players: 1 total; [class_746['Haui111'/90583, l='ClientLevel', x=-4811.05, y=71.64, z=-4636.12]]
	Chunk stats: 1024, 313
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,76,0), Section: (at 0,12,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 173595 game time, 11841781 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 448327320 bytes (427 MiB) / 1073741824 bytes (1024 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3,19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x249d
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3141
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512,00
	Graphics card #1 deviceId: 0x1638
	Graphics card #1 versionInfo: DriverVersion=31.0.14033.1012
	Graphics card #2 name: DisplayLink USB Device
	Graphics card #2 vendor: DisplayLink (0x17e9)
	Graphics card #2 VRAM (MB): 0,00
	Graphics card #2 deviceId: 0x6006
	Graphics card #2 versionInfo: DriverVersion=10.3.6400.0
	Graphics card #3 name: DisplayLink USB Device
	Graphics card #3 vendor: DisplayLink (0x17e9)
	Graphics card #3 VRAM (MB): 0,00
	Graphics card #3 deviceId: 0x6006
	Graphics card #3 versionInfo: DriverVersion=10.3.6400.0
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 3,20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 3,20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23709,31
	Virtual memory used (MB): 18027,91
	Swap memory total (MB): 7936,00
	Swap memory used (MB): 407,84
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		carpet: Carpet Mod 1.4.79
		cmdkeybind: Command Macros 1.6.2-1.19.4
			kyrptconfig: Kyrpt Config 1.5.2-1.19.4
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric: Fabric API 0.58.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.17
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.12.1
		lod: Distant Horizons 1.6.7a
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19
		phosphor: Phosphor 0.8.1
		replaymod: Replay Mod 1.19-2.6.10
		sodium: Sodium 0.4.2+replaymod.rev.bfbc6de
			org_joml_joml: joml 1.10.4
		worldeditcui: WorldEditCUI 1.19+01
		xaerominimap: Xaero's Minimap 22.12.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.17-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.41, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics

**Comment by Haui1112** [comment]
Nvm I downloaded a newer version than I should have.
